### ISSUE TITLE
toString on fresh SyslogMessageSenders causes NPE

### ISSUE THREAD

**Issue by lvh** [CloudBees-community/syslog-java-client#10]
Whenever I used `(TcpSyslogMessageSender.)` in my exploratory Clojure REPL session, I got NullPointerExceptions. I traced this back to the toString:

https://github.com/CloudBees-community/syslog-java-client/blob/master/src/main/java/com/cloudbees/syslog/sender/TcpSyslogMessageSender.java#L242

this.getSyslogServerHostname() will raise NPE on uninitialized objects, because it's implemented as:

```
 return syslogServerHostnameReference.get().getHostName();
```

I'm not sure if the correct behavior would be to catch that exception and return null in that method, or in toString; either way, NPEs when toStringing a fresh object is probably a bug. If we can reach consensus on the fix, I'd be happy to contribute it.

**Comment by cyrille-leclerc** [comment]
Thanks @lvh , syslog-java-client:1.0.8 has been released, it should soon be available on Maven Central.

**Comment by lvh** [comment]
Whoa, that's a pretty amazing response time. Thank you!!!

**Comment by cyrille-leclerc** [comment]
You're welcome!

On Wed, Jan 13, 2016 at 4:06 PM, lvh <notifications@github.com> wrote:

> Whoa, that's a pretty amazing response time. Thank you!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CloudBees-community/syslog-java-client/issues/10#issuecomment-171322827>
> .
>



-- 
Cyrille Le Clerc
email & gtalk : cleclerc@cloudbees.com / mob: +33-6.61.33.69.86 / skype:
cyrille.leclerc
CloudBees, Inc
www.cloudbees.com
