### ISSUE TITLE
TCP/UDP base class/interface

### ISSUE THREAD

**Issue by dstutz** [CloudBees-community/syslog-java-client#11]
Would it be possible to add an interface or class to the hierarchy so that I could use TCP/UDP interchangeably depending on application settings with the same message sending code?  AbstractSyslogMessageSender is close but does not have the 2 properties syslogServerName or syslogServerPort so I have to have 2 complete code blocks that are exactly the same except the type of the message sender being declared.

**Comment by cyrille-leclerc** [comment]
Solved by #29
