### ISSUE TITLE
Facility uses incorrect integer values

### ISSUE THREAD

**Issue by dhsmith1001** [CloudBees-community/syslog-java-client#14]
The Facility class uses integer values 0-23, multiplied by 8. This is incorrect, they are defined as 0-23. The time to multiply them by 8 is when calculating the Priority value, facility * 8 + severity, per RFC 5424 (https://tools.ietf.org/html/rfc5424#section-6.2.1).

**Comment by cyrille-leclerc** [comment]
Thanks for your PR
