### ISSUE TITLE
Support Octet Counting message transfer method

### ISSUE THREAD

**Issue by rbertoncelj** [CloudBees-community/syslog-java-client#22]
Support **Octet Counting** message transfer method as defined in [RFC 6587, section 3.4.1](https://tools.ietf.org/html/rfc6587#section-3.4.1) as an alternative to the older Non-Transparent-Framing method.

**Comment by hutson** [comment]
@rbertoncelj this appears to have been released as of version 1.1.4 - https://github.com/CloudBees-community/syslog-java-client/commit/8296e34faffa2f7959b19c31218da72011fba797

**Comment by rbertoncelj** [comment]
Oh, nice, thank you for the heads-up.
