### ISSUE TITLE
setSyslogServerHostname/setSyslogServerPort: could be declared in AbstractSyslogMessageSender

### ISSUE THREAD

**Issue by rosemead** [CloudBees-community/syslog-java-client#28]
Hi.
Just curious: is there a reason why a/m methods were not declared abstract in AbstractSyslogMessageSender?

**Comment by cyrille-leclerc** [comment]
@rosemead there is not specific reason. Can you share with us the use case that makes you desire this?

**Comment by cyrille-leclerc** [comment]
Shipped in 1.1.6
