### ISSUE TITLE
Not able to find "SyslogMessageUdpSender" source class for UDP RFC 5424

### ISSUE THREAD

**Issue by arjunpidugu642** [CloudBees-community/syslog-java-client#32]
Hi Sir,

I have used your Syslog Java Client with Maven and  able to execute all sample codes except "Sample UDP sender using RFC 5424" as SyslogMessageUdpSender class is not available.

I am not even able to see SyslogMessageUdpSender class in source folder.

Please check and let me know how can I use java maven client for UDP RFC 5424.

**Comment by cyrille-leclerc** [comment]
Please see updated documentation https://github.com/CloudBees-community/syslog-java-client
