### ISSUE TITLE
MessageFormat.RFC_5425 is not found in provided java syslog client

### ISSUE THREAD

**Issue by arjunpidugu642** [CloudBees-community/syslog-java-client#35]
Hi,

I have placed provided syslog java client
""" <dependency>
    <groupId>com.cloudbees</groupId>
    <artifactId>syslog-java-client</artifactId>
    <version>1.1.7</version>
</dependency>"""

I am not finding RFC_5425 message format and I am seeing same entry in source code.

Do i need to go for any latest version of syslog java client?

**Comment by cyrille-leclerc** [comment]
Please see updated documentation https://github.com/CloudBees-community/syslog-java-client
