### ISSUE TITLE
Does TcpSyslogMessageSender support self-signed certificates?

### ISSUE THREAD

**Issue by zharvey-bh** [CloudBees-community/syslog-java-client#47]
I am evaluating using this library to read a log file and send its contents off to a syslog receiver I've already built.

My _understanding_ is that `TcpSyslogMessageSender` can be used to send messages over TLS using SSL certificates. However I don't see any "trust" configurations anywhere, which makes me wonder if self-signed (non-CA-signed) certificates are supported by this library at all?

If my syslog receiver on the other end presents this client with a self-signed certificate, how can I configure the `TcpSyslogMessageSender` to trust it?

**Comment by cyrille-leclerc** [comment]
@zharvey-bh , as you can inject your own SSLContext, I think you can allow self signed certificates... See https://github.com/CloudBees-community/syslog-java-client/blob/syslog-java-client-1.1.7/src/main/java/com/cloudbees/syslog/sender/TcpSyslogMessageSender.java#L236

**Comment by zharvey-bh** [comment]
Interesting, thanks for the suggestion @cyrille-leclerc. I'm not familiar with the Java SSL API (and hence `SSLContext`) but will look for some code examples involving self-signed cert exampes. 👍  thanks again
