### ISSUE TITLE
README.md has errors in documentation

### ISSUE THREAD

**Issue by dfch** [CloudBees-community/syslog-java-client#6]
The headlines in the [README.md](https://github.com/CloudBees-community/syslog-java-client/blob/master/README.md) do not match the actual topic they are describing. In addition throughout the document (and in some comments within the project as well), the RFC3164 has a typo (spelled RFC3613)

**Comment by cyrille-leclerc** [comment]
Fixed by https://github.com/CloudBees-community/syslog-java-client/pull/13
