### ISSUE TITLE
RFC3164 timestamp are UTC instead of localtime

### ISSUE THREAD

**Issue by casta** [CloudBees-community/syslog-java-client#7]
Hi,

I noticed that the RFC3164 format is logging time as UTC.
But the RFC (http://tools.ietf.org/html/rfc3164#section-4.1.2) says it should be local time:

> The TIMESTAMP field is the **local time** and is in the format of "Mmm dd
> hh:mm:ss" (without the quote marks) 

https://github.com/CloudBees-community/syslog-java-client/blob/master/src/main/java/com/cloudbees/syslog/SyslogMessage.java#L75
The issue is the “TimeZone.getTimeZone("GMT"),” here. It should be “TimeZone.getDefault()”

**Comment by cyrille-leclerc** [comment]
Thanks, I just cut the release 1.0.7 so that you are not stuck. Sync to Maven Central Repo can take up to several hours.

https://github.com/CloudBees-community/syslog-java-client/releases/tag/syslog-java-client-1.0.7

**Comment by casta** [comment]
Great !
Thanks for your responsiveness !
